USER root
ENV YUMCONFIG=/etc/yum.repos.d/google-chrome.repo
COPY google-chrome.repo $YUMCONFIG
#--------------------------------------------------------
# Update the image with the latest packages (recommended)
#--------------------------------------------------------
RUN yum update -y; yum clean all
RUN rm -rf /var/cache/yum
RUN yum info google-chrome-stable
